"""add_discount

Revision ID: 12ad67f85c17
Revises: dd911b2229f2
Create Date: 2025-04-08 19:54:44.909910

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '12ad67f85c17'
down_revision: Union[str, None] = 'dd911b2229f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('discount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'discount')
    # ### end Alembic commands ###
