"""seed_data

Revision ID: dd911b2229f2
Revises: 5b2a6a59d6cd
Create Date: 2025-04-07 20:09:50.800912

"""
import random
from datetime import datetime, timedelta
from typing import Sequence, Union

from sqlalchemy import DateTime, ForeignKey, String
from sqlalchemy.orm import Mapped, Session, declarative_base, mapped_column

from alembic import op

Base = declarative_base()


class Category(Base):
    __tablename__ = "categories"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(100), nullable=False)


class Product(Base):
    __tablename__ = "products"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    category_id: Mapped[int] = mapped_column(ForeignKey("categories.id"), nullable=False)


class Sales(Base):
    __tablename__ = "sales"

    id: Mapped[int] = mapped_column(primary_key=True)
    product_id: Mapped[int] = mapped_column(ForeignKey("products.id"), nullable=False)
    amount: Mapped[int] = mapped_column(nullable=False)
    dt: Mapped[datetime] = mapped_column(DateTime(), nullable=False)


# revision identifiers, used by Alembic.
revision: str = 'dd911b2229f2'
down_revision: Union[str, None] = '5b2a6a59d6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаём сессию для работы с ORM
    bind = op.get_bind()
    session = Session(bind=bind)

    # 1. Добавляем категории
    categories = [
        Category(name="Electronics"),
        Category(name="Clothing"),
        Category(name="Books"),
    ]
    session.add_all(categories)
    session.flush()  # Чтобы получить ID категорий

    electronics_id = categories[0].id
    clothing_id = categories[1].id
    books_id = categories[2].id

    # 2. Добавляем товары
    products = [
        # Electronics (category_id=1)
        Product(name="Laptop", category_id=electronics_id),
        Product(name="Smartphone", category_id=electronics_id),
        Product(name="Headphones", category_id=electronics_id),
        Product(name="Smartwatch", category_id=electronics_id),
        Product(name="Tablet", category_id=electronics_id),

        # Clothing (category_id=2)
        Product(name="T-shirt", category_id=clothing_id),
        Product(name="Jeans", category_id=clothing_id),
        Product(name="Jacket", category_id=clothing_id),
        Product(name="Sneakers", category_id=clothing_id),
        Product(name="Hat", category_id=clothing_id),

        # Books (category_id=3)
        Product(name="Novel", category_id=books_id),
        Product(name="Sci-Fi Book", category_id=books_id),
        Product(name="Cookbook", category_id=books_id),
        Product(name="History Book", category_id=books_id),
        Product(name="Poetry Book", category_id=books_id),
    ]

    session.add_all(products)
    session.flush()  # Чтобы получить ID товаров

    # 3. Генерируем продажи за последние 6 месяцев
    sales = []
    today = datetime.now()
    six_months_ago = today - timedelta(days=180)

    for product_id in range(min(products, key=lambda p: p.id).id + 1, max(products, key=lambda p: p.id).id + 1):
        for _ in range(random.randint(5, 10)):  # 5-20 продаж на товар
            random_days_ago = random.randint(0, 180)
            sale_date = six_months_ago + timedelta(days=random_days_ago)
            sales.append(
                Sales(
                    product_id=product_id,
                    amount=random.randint(1, 10),
                    dt=sale_date,
                )
            )

    session.add_all(sales)
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE sales, products, categories RESTART IDENTITY CASCADE;")
    # ### end Alembic commands ###
